OmniAuth.config.logger = Rails.logger

ENV['FOURSQUARE_APP_ID'] = 'B3ZHOWCVIDJJVGXSAQCJLG235BB5V3RG4BEZ5GIZCCM5RH31'
ENV['FOURSQUARE_SECRET'] = 'IGVDU3YKCINXB0MOFIYA0MCUN1PJQABVXMHLLTIITKEGWNL4'

Rails.application.config.middleware.use OmniAuth::Builder do
  provider :foursquare, ENV['FOURSQUARE_APP_ID'], ENV['FOURSQUARE_SECRET']
end
